# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_userinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.CharField(blank=True, max_length=128, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(blank=True, help_text='格式yyyy-mm-dd', verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, max_length=64, verbose_name='所在区域'),
        ),
        migrations.AlterField(
            model_name='student',
            name='memo',
            field=models.CharField(blank=True, max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.CharField(blank=True, max_length=64, verbose_name='岗位'),
        ),
        migrations.AlterField(
            model_name='student',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='student',
            name='welfare',
            field=models.CharField(blank=True, max_length=256, verbose_name='福利'),
        ),
    ]
