# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171028_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(blank=True, help_text='格式yyyy-mm-dd', null=True, verbose_name='入职时间'),
        ),
    ]
